name: Build and Push py-kms

on:
  workflow_dispatch:    # 手动触发
  release:
    types: [published]  # 上游 release 发布触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ 检出代码
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: Py-KMS-Organization/py-kms
          ref: ${{ github.event.release.tag_name || 'main' }}

      # 2️⃣ 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ 登录 GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: wuwweizn
          password: ${{ secrets.GH_PAT }}

      # 4️⃣ 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5️⃣ 构建并推送镜像
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/wuwweizn/py-kms:${{ github.event.release.tag_name || 'manual' }}
            ghcr.io/wuwweizn/py-kms:latest
            ${{ secrets.DOCKER_USERNAME }}/py-kms:${{ github.event.release.tag_name || 'manual' }}
            ${{ secrets.DOCKER_USERNAME }}/py-kms:latest
