name: Build Image On Release

on:
  release:
    types: [ published ]
  pull_request:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: thespad/actions/.github/workflows/build-image.yml@v8.0.5
    with:
      repo_owner: "wuweizhineng@163.com"
      app_name: "py-kms"
      release_type: "github_commit"
      release_url: "https://api.github.com/repos/Py-KMS-Organization/py-kms/commits/master"
      dockerhub_user: "wuweizhineng@163.com"
      target-arch: "64"
      sign_image: false
    secrets:
      dockerhub_password: ${{ secrets.DOCKER_PASSWORD }}
